namespace Avarice.StaticData;

internal static class PositionalPotencies
{
    internal record Row(int Id, int Percent, bool IsHit, string Name, string Position, string Comment);

    internal static readonly Row[] Records =
    {
        //     Id  Percent  IsHit  ActionName               ActionPosition  Comment
        new(   56, 18, true,  "Snap Punch",            "flank", "50/90 Unbuffed"),
        new(   56, 14, true,  "Snap Punch",            "flank", "50 Buffed"),
        new(   56, 13, true,  "Snap Punch",            "flank", "60 buffed, 90 Buffed"),
        new(   56, 20, true,  "Snap Punch",            "flank", "60 Unbuffed"),
        new(   56, 12, true,  "Snap Punch",            "flank", "90 Buffed"),
        new(   66, 18, true,  "Demolish",              "rear",  "lv 50"),
        new(   66, 17, true,  "Demolish",              "rear",  "lv 50"),
        new(   66, 15, true,  "Demolish",              "rear",  "lv 90"),
        new(   66, 14, true,  "Demolish",              "rear",  "lv 100"),
        new(   79,  0, false, "Heavy Thrust",          "flank", "lol"),
        new(   88, 28, true,  "Chaos Thrust",          "rear",  "50 Uncomboed"),
        new(   88, 61, true,  "Chaos Thrust",          "rear",  "50 Comboed"),
        new( 2255, 70, true,  "Aeolian Edge",          "rear",  "31 Comboed"),
        new( 2255, 54, true,  "Aeolian Edge",          "rear",  "60 Uncomboed with Kazematoi"),
        new( 2255, 23, true,  "Aeolian Edge",          "rear",  "60 Comboed with Kazematoi"),
        new( 2255, 37, true,  "Aeolian Edge",          "rear",  "60 Comboed no Kazematoi"),
        new( 2255, 20, true,  "Aeolian Edge",          "rear",  "90 Uncomboed with Kazematoi"),
        new( 2255, 30, true,  "Aeolian Edge",          "rear",  "90 Uncomboed no Kazematoi"),
        new( 2255, 50, true,  "Aeolian Edge",          "rear",  "90 Comboed with Kazematoi"),
        new( 2255, 63, true,  "Aeolian Edge",          "rear",  "90 Comboed no Kazematoi"),
        new( 2255, 15, true,  "Aeolian Edge",          "rear",  "100 Uncomboed with Kazematoi"),
        new( 2255, 21, true,  "Aeolian Edge",          "rear",  "100 Uncomboed no Kazematoi"),
        new( 2255, 42, true,  "Aeolian Edge",          "rear",  "100 Comboed with Kazematoi"),
        new( 2255, 52, true,  "Aeolian Edge",          "rear",  "100 Comboed no Kazematoi"),
        new( 2258, 25, true,  "Trick Attack",          "rear",  ""),
        new( 3554, 28, true,  "Fang and Claw",         "flank", "90 Uncomboed"),
        new( 3554, 66, true,  "Fang and Claw",         "flank", "90 Comboed"),
        new( 3554, 22, true,  "Fang and Claw",         "flank", "100 Uncomboed"),
        new( 3554, 58, true,  "Fang and Claw",         "flank", "100 Comboed"),
        new( 3556, 28, true,  "Wheeling Thrust",       "rear",  "90 Uncomboed"),
        new( 3556, 66, true,  "Wheeling Thrust",       "rear",  "90 Comboed"),
        new( 3556, 22, true,  "Wheeling Thrust",       "rear",  "100 Uncomboed"),
        new( 3556, 58, true,  "Wheeling Thrust",       "rear",  "100 Comboed"),
        new( 3563, 30, true,  "Armor Crush",           "flank", "90 Uncomboed"),
        new( 3563, 65, true,  "Armor Crush",           "flank", "90 Comboed"),
        new( 3563, 20, true,  "Armor Crush",           "flank", "100 Uncomboed"),
        new( 3563, 52, true,  "Armor Crush",           "flank", "100 Comboed"),
        new( 3563, 37, true,  "Armor Crush",           "flank", "<74 Uncomboed"),
        new( 3563, 72, true,  "Armor Crush",           "flank", "<74 Comboed"),
        new( 7481, 33, true,  "Gekko",                 "rear",  "50 Uncomboed"),
        new( 7481, 72, true,  "Gekko",                 "rear",  "50 Comboed"),
        new( 7481, 31, true,  "Gekko",                 "rear",  "90 Uncomboed"),
        new( 7481, 70, true,  "Gekko",                 "rear",  "90 Comboed"),
        new( 7481, 23, true,  "Gekko",                 "rear",  "100 Uncomboed"),
        new( 7481, 61, true,  "Gekko",                 "rear",  "100 Comboed"),
        new( 7482, 33, true,  "Kasha",                 "flank", "50 Uncomboed"),
        new( 7482, 72, true,  "Kasha",                 "flank", "50 Comboed"),
        new( 7482, 31, true,  "Kasha",                 "flank", "90 Uncomboed"),
        new( 7482, 70, true,  "Kasha",                 "flank", "90 Comboed"),
        new( 7482, 23, true,  "Kasha",                 "flank", "100 Uncomboed"),
        new( 7482, 61, true,  "Kasha",                 "flank", "100 Comboed"),
        new(24382, 11, true,  "Gibbet",                "flank", "90 Enhanced"),
        new(24382, 13, true,  "Gibbet",                "flank", "90 Non-enhanced"),
        new(24382,  9, true,  "Gibbet",                "flank", "100 Enhanced"),
        new(24382, 10, true,  "Gibbet",                "flank", "100 Non-enhanced"),
        new(24383, 11, true,  "Gallows",               "rear",  "90 Enhanced"),
        new(24383, 13, true,  "Gallows",               "rear",  "90 Non-enhanced"),
        new(24383,  9, true,  "Gallows",               "rear",  "100 Enhanced"),
        new(24383, 10, true,  "Gallows",               "rear",  "100 Non-enhanced"),
        new(25772, 28, true,  "Chaotic Spring",        "rear",  "90 Uncomboed"),
        new(25772, 66, true,  "Chaotic Spring",        "rear",  "90 Comboed"),
        new(25772, 22, true,  "Chaotic Spring",        "rear",  "100 Uncomboed"),
        new(25772, 58, true,  "Chaotic Spring",        "rear",  "100 Comboed"),
        new(34610, 48, true,  "Flanksting Strike",     "flank", "100 Enhanced"),
        new(34610, 54, true,  "Flanksting Strike",     "flank", ""),
        new(34610, 60, true,  "Flanksting Strike",     "flank", "100 Non-enhanced"),
        new(34610, 70, true,  "Flanksting Strike",     "flank", ""),
        new(34610, 50, true,  "Flanksting Strike",     "flank", "80 ?"),
        new(34610, 63, true,  "Flanksting Strike",     "flank", "80 ?"),
        new(34611, 48, true,  "Flanksbane Fang",       "flank", "100 Enhanced"),
        new(34611, 54, true,  "Flanksbane Fang",       "flank", ""),
        new(34611, 60, true,  "Flanksbane Fang",       "flank", "100 Non-enhanced"),
        new(34611, 70, true,  "Flanksbane Fang",       "flank", ""),
        new(34611, 50, true,  "Flanksbane Fang",       "flank", "80 ?"),
        new(34611, 63, true,  "Flanksbane Fang",       "flank", "80 ?"),
        new(34612, 48, true,  "Hindsting Strike",      "rear",  "100 Enhanced"),
        new(34612, 54, true,  "Hindsting Strike",      "rear",  ""),
        new(34612, 60, true,  "Hindsting Strike",      "rear",  "100 Non-enhanced"),
        new(34612, 70, true,  "Hindsting Strike",      "rear",  ""),
        new(34612, 50, true,  "Hindsting Strike",      "rear",  "80 ?"),
        new(34612, 63, true,  "Hindsting Strike",      "rear",  "80 ?"),
        new(34613, 48, true,  "Hindsbane Fang",        "rear",  "100 Enhanced"),
        new(34613, 54, true,  "Hindsbane Fang",        "rear",  ""),
        new(34613, 60, true,  "Hindsbane Fang",        "rear",  "100 Non-enhanced"),
        new(34613, 70, true,  "Hindsbane Fang",        "rear",  ""),
        new(34613, 50, true,  "Hindsbane Fang",        "rear",  "80 ?"),
        new(34613, 63, true,  "Hindsbane Fang",        "rear",  "80 ?"),
        new(34621,  7, true,  "Hunter's Coil",         "flank", "lv 100"),
        new(34622,  7, true,  "Swiftskin's Coil",      "rear",  "lv 100"),
        new(36947, 16, true,  "Pouncing Coeurl",       "flank", "100 Unbuffed"),
        new(36947, 11, true,  "Pouncing Coeurl",       "flank", "100 Buffed"),
        new(36970,  7, true,  "Executioner's Gibbet",  "flank", ""),
        new(36971,  7, true,  "Executioner's Gallows", "rear",  ""),
    };
}
